### ISSUE TITLE
Looking forward to the full network code

### ISSUE THREAD

**Issue by forever-rz** [CVPR23/DQnet#1]
I recently read your paper and found it to be very intriguing.The work you have done is truly innovative.
I appreciate the time and effort you have already put into publishing your research.However, when I try to train and test, I get the following error, and I look forward to your help to solve this problem.
Thank you very much for your time and consideration
`Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/wtr/COD/DQnet-main/main.py", line 394, in <module>
    main()
  File "/mnt/wtr/COD/DQnet-main/main.py", line 361, in main
    model, model_code = builder.build_obj_from_registry(
  File "/mnt/wtr/COD/DQnet-main/utils/builder.py", line 31, in build_obj_from_registry
    assert obj_name in _registry, f"obj_name: {obj_name} must be contained in the registry:\n{_registry}"
AssertionError: obj_name: DQnet must be contained in the registry:
Registry of model:
Names               |Objects                                                     
python-BaseException`

**Comment by Zhangbeibei123** [comment]
我也是大概遇到了你的问题，经过我的分析，应该是缺少网络结构DQnet模型的文件，想问下是否我的分析是正确的，即他缺少DQnet的定义文件甚至是整个小项目
